<?php

namespace Database\Seeders;

use App\Models\Product;
use App\Models\ProductCategory;
use App\Models\ProductSpecification;
use App\Models\Setting;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Str;

class ElysiumCommoditiesSeeder extends Seeder
{
    public function run(): void
    {
        // 1. Synchronize Official Business Settings from Visiting Card
        $settings = [
            'company_name' => ['value' => 'Agro Dairy Export LLP', 'group' => 'general', 'label' => 'Company Name'],
            'contact_person' => ['value' => 'J.P. Vora', 'group' => 'contact', 'label' => 'Managing Partner / Export Director'],
            'tagline' => ['value' => 'Premier Agricultural Commodities & Dairy Export from India to Global Markets', 'group' => 'general', 'label' => 'Tagline'],
            'iec_code' => ['value' => '0817029381', 'group' => 'general', 'label' => 'Importer Exporter Code (IEC)'],
            'apeda_rcmc' => ['value' => 'APEDA/RCMC/2026/0892', 'group' => 'general', 'label' => 'APEDA Registration No.'],
            'fssai_licence' => ['value' => '10722026000148', 'group' => 'general', 'label' => 'FSSAI Central Licence No.'],
            'gstin' => ['value' => '24AAHFA3928L1Z9', 'group' => 'general', 'label' => 'GSTIN Number'],
            'head_office_address' => ['value' => 'Office No. -701, THE FUTURE CORNER, Sarthana, Surat- 395013, Gujarat, India', 'group' => 'contact', 'label' => 'Corporate Head Office Address'],
            'processing_plant_address' => ['value' => 'Saurashtra Processing Terminal, GIDC Industrial Estate, Gondal - 360311, Dist. Rajkot, Gujarat, India', 'group' => 'contact', 'label' => 'Processing & Sorting Terminal'],
            'primary_email' => ['value' => 'agrodairyexportllp@gmail.com', 'group' => 'contact', 'label' => 'Primary Export Email'],
            'secondary_email' => ['value' => 'agrodairyexportllp@gmail.com', 'group' => 'contact', 'label' => 'General Inquiries Email'],
            'primary_phone' => ['value' => '+91 90233 63680', 'group' => 'contact', 'label' => 'Direct Phone Hotline'],
            'whatsapp_number' => ['value' => '+919023363680', 'group' => 'whatsapp', 'label' => 'Official WhatsApp Number (E.164)'],
            'whatsapp_default_message' => ['value' => 'Hello J.P. Vora / Agro Dairy Export team, I am interested in sourcing agricultural commodities from India. Please share quotation details.', 'group' => 'whatsapp', 'label' => 'Default WhatsApp Message'],
            'loading_ports' => ['value' => 'Mundra Port (INMUN), Kandla Port (INIXY), Pipavav Port (INPAV) & Hazira Port (INHAZ), Gujarat, India', 'group' => 'general', 'label' => 'Gateway Exit Ports'],
            'business_hours' => ['value' => 'Monday - Saturday: 09:00 AM - 07:00 PM IST (Export Desk available 24/7 via WhatsApp)', 'group' => 'contact', 'label' => 'Business Hours'],
            'annual_export_volume' => ['value' => '50,000+ Metric Tons', 'group' => 'stats', 'label' => 'Annual Export Volume'],
            'countries_exported' => ['value' => '50+ Countries Worldwide', 'group' => 'stats', 'label' => 'Export Destinations'],
            'farmer_network_count' => ['value' => '15,000+ Contracted Farmers', 'group' => 'stats', 'label' => 'Direct Farmer Network'],
            'warehousing_capacity' => ['value' => '30,000 MT Modern Cold & Dry Storage', 'group' => 'stats', 'label' => 'Warehousing Capacity'],
        ];

        foreach ($settings as $key => $data) {
            Setting::updateOrCreate(['key' => $key], $data);
            Cache::forget("setting_{$key}");
        }

        // 2. Ten Comprehensive Agricultural Commodity Categories
        $categoriesData = [
            [
                'name' => 'Peanuts (Groundnuts)',
                'slug' => 'peanuts',
                'short_description' => 'Premium Bold, Java, Blanched Whole & Split, Diced, and In-Shell Groundnuts sourced with aflatoxin control.',
                'description' => 'Agro Dairy Export LLP is a leading processor and exporter of Indian Peanuts (Groundnuts). Sourced directly from Saurashtra mandis, our peanuts undergo computerized Buhler Sortex optical sorting, destoning, and dual gravity aspiration. Compliant with strict European Union (< 4 ppb aflatoxin), US FDA, and Gulf GCC standards.',
                'image' => '/images/categories/peanuts.jpg',
                'icon' => 'peanut',
                'hs_code_prefix' => '1202',
                'is_featured' => true,
                'sort_order' => 1,
            ],
            [
                'name' => 'Sesame Seeds',
                'slug' => 'sesame-seeds',
                'short_description' => 'Natural White 99/1, Auto-Sortex Hulled (99.95% & 99.98% purity), Black, and Brown Sesame Seeds.',
                'description' => 'We supply world-class Indian sesame seeds renowned for high natural oil content (48-50%) and distinct nutty fragrance. Our hulled sesame is produced through chemical-free water peeling, hot-air roasting dryers, and laser sorting to reach up to 99.98% commercial purity.',
                'image' => '/images/categories/sesame.jpg',
                'icon' => 'sparkles',
                'hs_code_prefix' => '1207',
                'is_featured' => true,
                'sort_order' => 2,
            ],
            [
                'name' => 'Peanut Butter & Spreads',
                'slug' => 'peanut-butter',
                'short_description' => 'Export Grade Creamy, Crunchy, Organic 100% Peanuts, and Bulk Industrial Pails & Drums.',
                'description' => 'Manufactured in an automated roasting and colloid milling facility. Available in retail glass and PET jars (200g to 1kg) with private labeling, as well as 20kg food-grade pails and 220kg steel drums for international bakeries, biscuit makers, and confectioners.',
                'image' => '/images/categories/peanut-butter.jpg',
                'icon' => 'cup-soda',
                'hs_code_prefix' => '2008.11',
                'is_featured' => true,
                'sort_order' => 3,
            ],
            [
                'name' => 'Indian Whole Spices',
                'slug' => 'spices',
                'short_description' => 'Machine Cleaned & Sortexed Cumin Seeds, Coriander, Fennel, Fenugreek, and High-Curcumin Turmeric.',
                'description' => 'Direct procurement from Asia’s premier spice hubs (Unjha, Ramganj, and Salem). Every batch is mechanically destoned, cleaned, color-sorted, and offered with ETO / Steam sterilization for export to Europe, USA, and Middle Eastern markets.',
                'image' => '/images/categories/spices.jpg',
                'icon' => 'flame',
                'hs_code_prefix' => '0909',
                'is_featured' => true,
                'sort_order' => 4,
            ],
            [
                'name' => 'Herbs & Specialty Seeds',
                'slug' => 'herbs-seeds',
                'short_description' => 'Chia Seeds, Psyllium Husk (Isabgol 95%/98%), Sun-Dried Ginger, and Whole Mustard Seeds.',
                'description' => 'High-purity botanical and specialty seeds sourced from Gujarat and Rajasthan agricultural belts. Cleaned to 99.5%+ purity, meeting international pharmacopoeia standards and food-grade nutraceutical specifications.',
                'image' => '/images/categories/herbs.jpg',
                'icon' => 'sparkles',
                'hs_code_prefix' => '1211',
                'is_featured' => true,
                'sort_order' => 5,
            ],
            [
                'name' => 'Chickpeas (Garbanzo Beans)',
                'slug' => 'chickpeas',
                'short_description' => 'Jumbo Kabuli Chickpeas (40/42, 42/44 count), Desi Chickpeas, and Crispy Roasted Split Chana.',
                'description' => 'Graded by seed millimeter caliber and count per ounce. Bright cream, uniform size, zero foreign matter, and high hydration ratio favored by Mediterranean canning and culinary packaging houses.',
                'image' => '/images/categories/chickpeas.jpg',
                'icon' => 'circle',
                'hs_code_prefix' => '0713.20',
                'is_featured' => true,
                'sort_order' => 6,
            ],
            [
                'name' => 'Pulses & Lentils',
                'slug' => 'pulses-lentils',
                'short_description' => 'Whole Green Moong, Split Moong Mogar, Green Lentils, Green Peas, Toor Dal, and Urad Dal.',
                'description' => 'Machine cleaned, polished, and moisture-balanced whole and split pulses. Sourced from high-protein harvests across Central and Western India for global food packaging and retail distribution.',
                'image' => '/images/categories/pulses.jpg',
                'icon' => 'circle-dot',
                'hs_code_prefix' => '0713',
                'is_featured' => true,
                'sort_order' => 7,
            ],
            [
                'name' => 'Dehydrated Vegetables',
                'slug' => 'dehydrated-vegetables',
                'short_description' => 'Dehydrated White & Red Onion Flakes, Minced, Powder, and Garlic Flakes, Granules & Powder.',
                'description' => 'Processed in Mahuva, Gujarat—the onion processing heartland of India. Dehydrated at controlled temperatures to preserve pungent allicin aroma, crisp texture, and low microbial counts.',
                'image' => '/images/categories/dehydrated.jpg',
                'icon' => 'utensils',
                'hs_code_prefix' => '0712',
                'is_featured' => true,
                'sort_order' => 8,
            ],
            [
                'name' => 'Grains & Milling Products',
                'slug' => 'grains-milling',
                'short_description' => 'Milling Wheat, Non-GMO Yellow Corn / Maize, Corn Grits & Flour, and Pearl Millet (Bajra).',
                'description' => 'Bulk grains from certified silos across Western India. High hectolitre weight, high falling numbers, and low moisture suited for commercial flour mills, breakfast cereal manufacturers, and snack processors.',
                'image' => '/images/categories/grains.jpg',
                'icon' => 'wheat',
                'hs_code_prefix' => '1001',
                'is_featured' => true,
                'sort_order' => 9,
            ],
            [
                'name' => 'Animal Feed & Oil Meals',
                'slug' => 'animal-feed',
                'short_description' => 'Corn DDGS (28% Protein), De-Oiled Soybean Meal (DOC Hi-Pro 46-48%), DORB, and Rapeseed Meal.',
                'description' => 'High-digestibility, protein-dense animal nutrition ingredients for poultry feed, aquaculture, and dairy cattle formulators in South East Asia, Middle East, and East Africa.',
                'image' => '/images/categories/animal-feed.jpg',
                'icon' => 'shield-check',
                'hs_code_prefix' => '2304',
                'is_featured' => true,
                'sort_order' => 10,
            ],
        ];

        $categories = [];
        foreach ($categoriesData as $c) {
            $categories[$c['slug']] = ProductCategory::updateOrCreate(
                ['slug' => $c['slug']],
                array_merge($c, [
                    'is_active' => true,
                    'meta_title' => "{$c['name']} Exporter from India | Agro Dairy Export LLP",
                    'meta_description' => Str::limit($c['short_description'], 155),
                ])
            );
        }

        // 3. Full 48 Commodity Catalog with Detailed Specifications
        $products = [
            // PEANUTS (GROUNDNUTS)
            [
                'category' => 'peanuts',
                'name' => 'Bold Peanuts (Groundnut Kernels)',
                'slug' => 'bold-peanuts',
                'sku' => 'ADE-PN-BLD',
                'short_description' => 'Long-kernel Bold peanuts with reddish-brown skin, high oil content, and premium crunch.',
                'description' => 'Bold Peanuts from Saurashtra, Gujarat, are world-renowned for their rich flavor and large kernel size. Mechanically destoned, graded, Sortexed, and packed under aflatoxin-controlled conditions meeting EU and Gulf food standards.',
                'origin' => 'Gujarat, India',
                'grade_variety' => 'Bold 38/42, 40/50, 50/60, 60/70 Counts/Oz',
                'hs_code' => '1202.42.10',
                'moq' => 19.00,
                'moq_unit' => 'MT (1 x 20ft FCL)',
                'available_quantity' => '6,000 MT Annual',
                'shelf_life' => '12 Months',
                'storage_conditions' => 'Cool, dry, ventilated storage below 18°C and 65% RH',
                'packaging_summary' => '25kg / 50kg PP Woven or Jute Bags, 25kg Vacuum Bags in Cartons',
                'loading_summary' => '19 MT in 20ft FCL (Bags), 26 MT in 40ft FCL',
                'is_featured' => true,
                'specs' => [
                    ['spec_group' => 'Physical Parameters', 'parameter' => 'Count Per Ounce', 'value' => '38/42, 40/50, 50/60', 'unit' => 'Counts/Oz', 'test_method' => 'Manual Count'],
                    ['spec_group' => 'Physical Parameters', 'parameter' => 'Purity', 'value' => '99.0% Min', 'unit' => '%', 'test_method' => 'IS 1155'],
                    ['spec_group' => 'Physical Parameters', 'parameter' => 'Moisture', 'value' => '7.0% Max', 'unit' => '%', 'test_method' => 'AOAC 925.10'],
                    ['spec_group' => 'Physical Parameters', 'parameter' => 'Admixture / Foreign Matter', 'value' => '0.5% - 1.0% Max', 'unit' => '%', 'test_method' => 'Gravimetric'],
                    ['spec_group' => 'Chemical Parameters', 'parameter' => 'Oil Content', 'value' => '48.0% - 50.0% Min', 'unit' => '%', 'test_method' => 'Soxhlet Extraction'],
                    ['spec_group' => 'Food Safety', 'parameter' => 'Aflatoxin (Total B1+B2+G1+G2)', 'value' => '< 4 ppb (EU) / < 15 ppb (US)', 'unit' => 'ppb', 'test_method' => 'HPLC-FLD'],
                ],
            ],
            [
                'category' => 'peanuts',
                'name' => 'Java Peanuts (Spanish Type)',
                'slug' => 'java-peanuts',
                'sku' => 'ADE-PN-JAV',
                'short_description' => 'Round shaped, pink skin Java peanuts favored for snacking, confectionery, and peanut butter.',
                'description' => 'Java Peanuts feature uniform round kernels with tender pinkish skins and sweet natural nutty taste. Ideal for roasting, honey-coating, and processing into silky smooth peanut butter.',
                'origin' => 'Gujarat & Rajasthan, India',
                'grade_variety' => 'Java 45/55, 50/60, 60/70, 70/80, 80/90 Counts/Oz',
                'hs_code' => '1202.42.20',
                'moq' => 19.00,
                'moq_unit' => 'MT (1 x 20ft FCL)',
                'available_quantity' => '5,000 MT Annual',
                'shelf_life' => '12 Months',
                'storage_conditions' => 'Cool dry warehouse',
                'packaging_summary' => '25kg / 50kg Jute Bags, PP Woven Bags, Vacuum Packs',
                'loading_summary' => '19 MT in 20ft FCL',
                'is_featured' => true,
                'specs' => [
                    ['spec_group' => 'Physical Parameters', 'parameter' => 'Counts per Ounce', 'value' => '50/60, 60/70, 70/80, 80/90', 'unit' => 'Count/Oz', 'test_method' => 'Manual Count'],
                    ['spec_group' => 'Physical Parameters', 'parameter' => 'Purity', 'value' => '99.0% Min', 'unit' => '%', 'test_method' => 'IS 1155'],
                    ['spec_group' => 'Physical Parameters', 'parameter' => 'Moisture', 'value' => '7.0% Max', 'unit' => '%', 'test_method' => 'AOAC 925.10'],
                    ['spec_group' => 'Chemical Parameters', 'parameter' => 'Oil Content', 'value' => '48.0% Min', 'unit' => '%', 'test_method' => 'Soxhlet'],
                    ['spec_group' => 'Food Safety', 'parameter' => 'Aflatoxin Total', 'value' => '< 4 ppb / < 10 ppb / < 20 ppb', 'unit' => 'ppb', 'test_method' => 'HPLC'],
                ],
            ],
            [
                'category' => 'peanuts',
                'name' => 'Blanched Peanuts (Whole Kernels)',
                'slug' => 'blanched-peanuts',
                'sku' => 'ADE-PN-BLN',
                'short_description' => 'Ivory-white blanched whole peanuts with skins removed through gentle hot-air blanching.',
                'description' => 'Precision air-blanched whole groundnut kernels. 100% skinless, destoned, optical color-sorted, and packaged in airtight vacuum bags to prevent oxidation and ensure prolonged crunch.',
                'origin' => 'Gujarat, India',
                'grade_variety' => 'Blanched Bold & Java 40/50, 50/60 Count/Oz',
                'hs_code' => '1202.42.90',
                'moq' => 19.00,
                'moq_unit' => 'MT (1 x 20ft FCL)',
                'available_quantity' => '3,500 MT',
                'shelf_life' => '12 Months (Vacuum Pack)',
                'storage_conditions' => 'Temperature controlled cold storage (< 15°C)',
                'packaging_summary' => '25kg Vacuum Bags inside heavy-duty 5-ply cartons',
                'loading_summary' => '19 MT in 20ft FCL (Cartons on pallets)',
                'is_featured' => true,
                'specs' => [
                    ['spec_group' => 'Physical Parameters', 'parameter' => 'Residual Skin', 'value' => '< 1.0% Max', 'unit' => '%', 'test_method' => 'Visual Sort'],
                    ['spec_group' => 'Physical Parameters', 'parameter' => 'Moisture', 'value' => '5.0% Max', 'unit' => '%', 'test_method' => 'AOAC 925.10'],
                    ['spec_group' => 'Physical Parameters', 'parameter' => 'Split Kernels', 'value' => '< 5.0% Max', 'unit' => '%', 'test_method' => 'Gravimetric'],
                    ['spec_group' => 'Food Safety', 'parameter' => 'Aflatoxin', 'value' => '< 4 ppb', 'unit' => 'ppb', 'test_method' => 'HPLC'],
                ],
            ],
            [
                'category' => 'peanuts',
                'name' => 'Split Blanched Peanuts',
                'slug' => 'split-blanched-peanuts',
                'sku' => 'ADE-PN-SBL',
                'short_description' => 'Cleanly split, skinless blanched peanut halves engineered for confectionery and paste milling.',
                'description' => 'Uniformly split and blanched peanut halves with hearts/germs separated if required. The cost-effective choice for peanut butter manufacturers, bakery bars, nougat, and candy toppings.',
                'origin' => 'Gujarat, India',
                'grade_variety' => 'Split Blanched Bold / Java',
                'hs_code' => '1202.42.90',
                'moq' => 19.00,
                'moq_unit' => 'MT',
                'available_quantity' => '2,500 MT',
                'shelf_life' => '12 Months',
                'storage_conditions' => 'Cool and dry conditions',
                'packaging_summary' => '25kg Vacuum Bags in Cartons / 25kg PP bags',
                'loading_summary' => '19 MT in 20ft FCL',
                'is_featured' => false,
                'specs' => [
                    ['spec_group' => 'Physical Parameters', 'parameter' => 'Skin Residue', 'value' => '< 1.5% Max', 'unit' => '%', 'test_method' => 'Visual'],
                    ['spec_group' => 'Physical Parameters', 'parameter' => 'Moisture', 'value' => '5.5% Max', 'unit' => '%', 'test_method' => 'AOAC'],
                    ['spec_group' => 'Food Safety', 'parameter' => 'Aflatoxin Total', 'value' => '< 4 ppb', 'unit' => 'ppb', 'test_method' => 'HPLC'],
                ],
            ],
            [
                'category' => 'peanuts',
                'name' => 'Diced / Chopped Roasted Peanuts',
                'slug' => 'diced-peanuts',
                'sku' => 'ADE-PN-DIC',
                'short_description' => 'Evenly diced roasted peanut granules (2-4mm / 4-6mm) for ice cream, baked goods, and snacking.',
                'description' => 'Golden-roasted blanched peanuts chopped and sieved to uniform granulations. Zero flour dust, roasted to desired color profile (light, medium, dark), with nitrogen flushing to maintain freshness.',
                'origin' => 'Gujarat, India',
                'grade_variety' => 'Granule Sizes: 2-4 mm, 4-6 mm, 6-8 mm',
                'hs_code' => '2008.11.00',
                'moq' => 10.00,
                'moq_unit' => 'MT',
                'available_quantity' => '1,500 MT',
                'shelf_life' => '9 Months',
                'storage_conditions' => 'Airtight packaging below 18°C',
                'packaging_summary' => '10kg / 15kg Nitrogen Flushed Barrier Foil Bags in Cartons',
                'loading_summary' => '16 MT in 20ft FCL',
                'is_featured' => false,
                'specs' => [
                    ['spec_group' => 'Physical Parameters', 'parameter' => 'Fines / Meal Dust', 'value' => '< 2.0% Max', 'unit' => '%', 'test_method' => 'Sieve Analysis'],
                    ['spec_group' => 'Physical Parameters', 'parameter' => 'Moisture', 'value' => '3.0% Max', 'unit' => '%', 'test_method' => 'AOAC'],
                    ['spec_group' => 'Chemical Parameters', 'parameter' => 'Peroxide Value', 'value' => '< 2.0 meq/kg', 'unit' => 'meq/kg', 'test_method' => 'AOCS'],
                ],
            ],
            [
                'category' => 'peanuts',
                'name' => 'In-Shell Groundnuts (Peanut Pods)',
                'slug' => 'in-shell-peanuts',
                'sku' => 'ADE-PN-INS',
                'short_description' => 'Sun-dried, mechanically cleaned two-kernel peanut pods with bright golden shells.',
                'description' => 'Natural double-pod in-shell peanuts. Gently washed, air-dried, and sorted to discard single-seed or damaged pods. Highly popular for wet-boiling, roasting in shell, and festive wholesale snacking.',
                'origin' => 'Gujarat, India',
                'grade_variety' => 'Pod Counts: 18/22, 22/26 pods per ounce',
                'hs_code' => '1202.41.10',
                'moq' => 14.00,
                'moq_unit' => 'MT (1 x 40ft HC)',
                'available_quantity' => '2,000 MT',
                'shelf_life' => '12 Months',
                'storage_conditions' => 'Dry, well-ventilated dry warehouse',
                'packaging_summary' => '25kg / 30kg Jute Bags or Mesh Bags',
                'loading_summary' => '14 MT in 40ft HC Container (Volumetric limit)',
                'is_featured' => false,
                'specs' => [
                    ['spec_group' => 'Physical Parameters', 'parameter' => 'Moisture', 'value' => '8.0% Max', 'unit' => '%', 'test_method' => 'AOAC'],
                    ['spec_group' => 'Physical Parameters', 'parameter' => 'Empty / Pop Pods', 'value' => '< 2.0% Max', 'unit' => '%', 'test_method' => 'Manual Count'],
                    ['spec_group' => 'Physical Parameters', 'parameter' => 'Damaged Pods', 'value' => '< 1.5% Max', 'unit' => '%', 'test_method' => 'Visual Sort'],
                ],
            ],

            // SESAME SEEDS
            [
                'category' => 'sesame-seeds',
                'name' => 'Natural White Sesame Seeds',
                'slug' => 'natural-white-sesame-seeds',
                'sku' => 'ADE-SS-NAT',
                'short_description' => 'Golden-cream natural white sesame seeds with rich essential oil content (48-50%).',
                'description' => 'Harvested from Gujarat’s coastal and canal belt. Cleaned over fine-air destoners and gravity separators to reach 99/1 or 99/1/1 purity grades. Preferred worldwide for tahini paste, bakery crusts, and cooking oil pressing.',
                'origin' => 'Gujarat, India',
                'grade_variety' => '99/1, 99/1/1, Machine Cleaned / Sortex Cleaned',
                'hs_code' => '1207.40.90',
                'moq' => 19.00,
                'moq_unit' => 'MT (1 x 20ft FCL)',
                'available_quantity' => '4,000 MT',
                'shelf_life' => '12 Months',
                'storage_conditions' => 'Cool and dry warehouse below 20°C',
                'packaging_summary' => '25kg / 50kg PP Woven Bags, Paper Bags with PE liner',
                'loading_summary' => '19 MT in 20ft FCL',
                'is_featured' => true,
                'specs' => [
                    ['spec_group' => 'Physical Parameters', 'parameter' => 'Purity', 'value' => '99.0% / 99.5% Min', 'unit' => '%', 'test_method' => 'IS 1155'],
                    ['spec_group' => 'Physical Parameters', 'parameter' => 'Moisture', 'value' => '6.0% Max', 'unit' => '%', 'test_method' => 'AOAC 925.10'],
                    ['spec_group' => 'Physical Parameters', 'parameter' => 'Admixture', 'value' => '0.5% - 1.0% Max', 'unit' => '%', 'test_method' => 'Gravimetric'],
                    ['spec_group' => 'Chemical Parameters', 'parameter' => 'Oil Content', 'value' => '48.0% - 50.0% Min', 'unit' => '%', 'test_method' => 'Soxhlet'],
                    ['spec_group' => 'Chemical Parameters', 'parameter' => 'Free Fatty Acids (FFA)', 'value' => '1.5% Max', 'unit' => '%', 'test_method' => 'AOCS'],
                ],
            ],
            [
                'category' => 'sesame-seeds',
                'name' => 'Hulled Sesame Seeds (Auto-Sortex 99.95% / 99.98%)',
                'slug' => 'hulled-sesame-seeds',
                'sku' => 'ADE-SS-HLD',
                'short_description' => 'Snow-white mechanically hulled sesame seeds with 99.95% and 99.98% premium purity.',
                'description' => 'Processed in an advanced wet-hulling facility using potable water and hygienic friction dehullers without caustic chemicals. Dried in continuous hot-air fluid bed dryers and triple Sortex laser sorted for pristine snow-white confectionery topping.',
                'origin' => 'Gujarat, India',
                'grade_variety' => 'Auto-Sortex Hulled 99.95% & 99.98% Purity',
                'hs_code' => '1207.40.10',
                'moq' => 19.00,
                'moq_unit' => 'MT (1 x 20ft FCL)',
                'available_quantity' => '3,500 MT',
                'shelf_life' => '12 Months',
                'storage_conditions' => 'Dry, ventilated, free from insect infestation',
                'packaging_summary' => '25kg Multi-wall Paper Bags with PE liner, 25kg PP Bags, or 1000kg Big Bags',
                'loading_summary' => '19 MT in 20ft FCL',
                'is_featured' => true,
                'specs' => [
                    ['spec_group' => 'Physical Parameters', 'parameter' => 'Purity', 'value' => '99.95% / 99.98% Min', 'unit' => '%', 'test_method' => 'IS 1155'],
                    ['spec_group' => 'Physical Parameters', 'parameter' => 'Moisture', 'value' => '4.5% - 5.0% Max', 'unit' => '%', 'test_method' => 'AOAC 925.10'],
                    ['spec_group' => 'Physical Parameters', 'parameter' => 'Dark / Unhulled Seeds', 'value' => '< 0.02% - 0.05% Max', 'unit' => '%', 'test_method' => 'Count on Lightboard'],
                    ['spec_group' => 'Chemical Parameters', 'parameter' => 'Oil Content', 'value' => '50.0% Min', 'unit' => '%', 'test_method' => 'Soxhlet'],
                    ['spec_group' => 'Chemical Parameters', 'parameter' => 'FFA', 'value' => '1.0% Max', 'unit' => '%', 'test_method' => 'Titration'],
                    ['spec_group' => 'Microbiological', 'parameter' => 'Salmonella', 'value' => 'Absent in 25g', 'unit' => '/25g', 'test_method' => 'ISO 6579'],
                ],
            ],
            [
                'category' => 'sesame-seeds',
                'name' => 'Black Sesame Seeds',
                'slug' => 'black-sesame-seeds',
                'sku' => 'ADE-SS-BLK',
                'short_description' => 'Deep black, glossy Sortex-cleaned sesame seeds prized for Asian gourmet cooking and bakery.',
                'description' => 'Naturally cultivated black sesame with intense nutty profile and rich antioxidant sesamin levels. Cleaned over gravity tables and high-resolution monochromatic optical sorters.',
                'origin' => 'Gujarat & Madhya Pradesh, India',
                'grade_variety' => 'Sortex Cleaned 99.5% & 99.9% Purity',
                'hs_code' => '1207.40.90',
                'moq' => 10.00,
                'moq_unit' => 'MT',
                'available_quantity' => '1,800 MT',
                'shelf_life' => '12 Months',
                'storage_conditions' => 'Cool dry warehouse',
                'packaging_summary' => '25kg Paper / PP Woven Bags',
                'loading_summary' => '19 MT in 20ft FCL',
                'is_featured' => false,
                'specs' => [
                    ['spec_group' => 'Physical Parameters', 'parameter' => 'Purity', 'value' => '99.5% - 99.9% Min', 'unit' => '%', 'test_method' => 'IS 1155'],
                    ['spec_group' => 'Physical Parameters', 'parameter' => 'Other Colored Seeds', 'value' => '< 0.5% Max', 'unit' => '%', 'test_method' => 'Visual Sort'],
                    ['spec_group' => 'Chemical Parameters', 'parameter' => 'Oil Content', 'value' => '47.0% Min', 'unit' => '%', 'test_method' => 'Soxhlet'],
                ],
            ],
            [
                'category' => 'sesame-seeds',
                'name' => 'Brown Sesame Seeds',
                'slug' => 'brown-sesame-seeds',
                'sku' => 'ADE-SS-BRN',
                'short_description' => 'Natural Gujarat brown sesame seeds, ideal for oil crushing and savory tahini paste.',
                'description' => 'High-oil natural brown sesame with rich flavor profile. Highly prized for cold-pressed sesame oil production and traditional sesame sweets across the Middle East and East Asia.',
                'origin' => 'Gujarat, India',
                'grade_variety' => 'Machine Cleaned 98/2 and 99/1 Purity',
                'hs_code' => '1207.40.90',
                'moq' => 19.00,
                'moq_unit' => 'MT',
                'available_quantity' => '2,200 MT',
                'shelf_life' => '12 Months',
                'storage_conditions' => 'Standard dry warehouse',
                'packaging_summary' => '25kg / 50kg PP Woven Bags',
                'loading_summary' => '19 MT in 20ft FCL',
                'is_featured' => false,
                'specs' => [
                    ['spec_group' => 'Physical Parameters', 'parameter' => 'Purity', 'value' => '98.5% - 99.0% Min', 'unit' => '%', 'test_method' => 'IS 1155'],
                    ['spec_group' => 'Chemical Parameters', 'parameter' => 'Oil Content', 'value' => '49.0% Min', 'unit' => '%', 'test_method' => 'Soxhlet'],
                    ['spec_group' => 'Physical Parameters', 'parameter' => 'Moisture', 'value' => '6.0% Max', 'unit' => '%', 'test_method' => 'AOAC'],
                ],
            ],

            // PEANUT BUTTER
            [
                'category' => 'peanut-butter',
                'name' => 'Creamy Peanut Butter',
                'slug' => 'creamy-peanut-butter',
                'sku' => 'ADE-PB-CRM',
                'short_description' => 'Velvety smooth, ultra-rich peanut butter made from roasted Gujarat Java & Bold peanuts.',
                'description' => 'Milled in high-speed micro-colloid mills to achieve a velvety 25-micron particle finish. Customizable with stabilizer (RSPO palm or hydrogenated rapeseed) or 100% natural pure recipe.',
                'origin' => 'Gujarat, India',
                'grade_variety' => 'Standard Creamy / No Added Sugar / Organic options',
                'hs_code' => '2008.11.00',
                'moq' => 5.00,
                'moq_unit' => 'MT',
                'available_quantity' => '1,500 MT',
                'shelf_life' => '18 Months',
                'storage_conditions' => 'Ambient room temperature away from direct sunlight',
                'packaging_summary' => 'Retail Jars (340g, 510g, 1kg PET/Glass), 20kg Food-Grade Pails, 220kg Drums',
                'loading_summary' => '18 MT in 20ft FCL (Palletized Cartons)',
                'is_featured' => true,
                'specs' => [
                    ['spec_group' => 'Composition', 'parameter' => 'Roasted Peanuts', 'value' => '90.0% - 100.0%', 'unit' => '%', 'test_method' => 'Recipe Spec'],
                    ['spec_group' => 'Physical Parameters', 'parameter' => 'Grind Fineness', 'value' => '< 30 microns', 'unit' => 'µm', 'test_method' => 'Micrometer'],
                    ['spec_group' => 'Nutritional', 'parameter' => 'Protein Content', 'value' => '25.0g - 28.0g / 100g', 'unit' => 'g/100g', 'test_method' => 'Kjeldahl'],
                    ['spec_group' => 'Microbiology', 'parameter' => 'Aflatoxin Total', 'value' => '< 4 ppb', 'unit' => 'ppb', 'test_method' => 'HPLC'],
                    ['spec_group' => 'Microbiology', 'parameter' => 'Salmonella', 'value' => 'Negative in 375g', 'unit' => '/375g', 'test_method' => 'FDA BAM'],
                ],
            ],
            [
                'category' => 'peanut-butter',
                'name' => 'Crunchy Peanut Butter',
                'slug' => 'crunchy-peanut-butter',
                'sku' => 'ADE-PB-CRN',
                'short_description' => 'Smooth roasted peanut butter base embedded with crispy golden roasted peanut nibs.',
                'description' => 'Features roasted diced peanut bits evenly suspended in smooth creamy peanut butter. Provides delightful crunchy texture and high satiety for breakfast spreads and energy snacks.',
                'origin' => 'Gujarat, India',
                'grade_variety' => 'Crunchy Granulated Blend',
                'hs_code' => '2008.11.00',
                'moq' => 5.00,
                'moq_unit' => 'MT',
                'available_quantity' => '1,200 MT',
                'shelf_life' => '18 Months',
                'storage_conditions' => 'Store below 25°C',
                'packaging_summary' => '340g, 500g, 1kg Jars, 20kg Buckets',
                'loading_summary' => '18 MT in 20ft FCL',
                'is_featured' => false,
                'specs' => [
                    ['spec_group' => 'Composition', 'parameter' => 'Peanut Granules Fraction', 'value' => '12.0% - 15.0%', 'unit' => '%', 'test_method' => 'Formulation'],
                    ['spec_group' => 'Nutritional', 'parameter' => 'Protein', 'value' => '26.0g / 100g', 'unit' => 'g', 'test_method' => 'Kjeldahl'],
                    ['spec_group' => 'Food Safety', 'parameter' => 'Aflatoxin Total', 'value' => '< 4 ppb', 'unit' => 'ppb', 'test_method' => 'HPLC'],
                ],
            ],
            [
                'category' => 'peanut-butter',
                'name' => 'Bulk Industrial Peanut Butter (Pails & Drums)',
                'slug' => 'bulk-industrial-peanut-butter',
                'sku' => 'ADE-PB-IND',
                'short_description' => 'B2B formulation engineered for industrial bakeries, confectioneries, and ice cream makers.',
                'description' => 'Shipped in heavy-duty 20kg HDPE pails with tamper-proof pull-tabs and 220kg epoxy-lined steel drums. Formulated for pumpability in automated factory dosing lines.',
                'origin' => 'Gujarat, India',
                'grade_variety' => 'Industrial Smooth 100% Peanuts',
                'hs_code' => '2008.11.00',
                'moq' => 10.00,
                'moq_unit' => 'MT',
                'available_quantity' => '2,000 MT',
                'shelf_life' => '12 Months',
                'storage_conditions' => 'Cool factory warehouse',
                'packaging_summary' => '20kg Food-Grade HDPE Buckets / 220kg Steel Drums',
                'loading_summary' => '18 MT in 20ft FCL',
                'is_featured' => false,
                'specs' => [
                    ['spec_group' => 'Composition', 'parameter' => 'Pure Peanuts', 'value' => '99.5% - 100.0%', 'unit' => '%', 'test_method' => 'Formulation'],
                    ['spec_group' => 'Physical Parameters', 'parameter' => 'Viscosity @ 40°C', 'value' => '3,500 - 5,000 cPs', 'unit' => 'cPs', 'test_method' => 'Brookfield Viscometer'],
                ],
            ],

            // INDIAN WHOLE SPICES
            [
                'category' => 'spices',
                'name' => 'Cumin Seeds (Jeera)',
                'slug' => 'cumin-seeds',
                'sku' => 'ADE-SP-CUM',
                'short_description' => 'Unjha mandi sourced Cumin Seeds, Machine Cleaned & Sortexed 99% / 99.5% purity.',
                'description' => 'India produces over 70% of the world’s cumin, and Gujarat’s Unjha mandi is the global trade nucleus. Our cumin seeds are mechanically cleaned, air-destoned, Sortexed, and analyzed for pesticide residues and volatile oil (2.5% to 3.5% min).',
                'origin' => 'Unjha, Gujarat, India',
                'grade_variety' => 'Singapore 99%, Europe 99.5%, ETO / Steam Sterilized',
                'hs_code' => '0909.31.29',
                'moq' => 14.00,
                'moq_unit' => 'MT (1 x 20ft FCL)',
                'available_quantity' => '3,000 MT',
                'shelf_life' => '24 Months',
                'storage_conditions' => 'Airtight packaging in cool, dry warehouse',
                'packaging_summary' => '25kg / 50kg PP Woven Bags, Jute Bags, Paper Bags with PE barrier',
                'loading_summary' => '14 MT in 20ft FCL (Bags), 26 MT in 40ft FCL',
                'is_featured' => true,
                'specs' => [
                    ['spec_group' => 'Physical Parameters', 'parameter' => 'Purity', 'value' => '99.0% / 99.5% Min', 'unit' => '%', 'test_method' => 'ASTA Cleanliness'],
                    ['spec_group' => 'Physical Parameters', 'parameter' => 'Moisture', 'value' => '8.0% - 9.0% Max', 'unit' => '%', 'test_method' => 'ASTA 2.0'],
                    ['spec_group' => 'Chemical Parameters', 'parameter' => 'Volatile Oil', 'value' => '2.5% - 3.5% Min', 'unit' => '% v/w', 'test_method' => 'Steam Distillation'],
                    ['spec_group' => 'Chemical Parameters', 'parameter' => 'Total Ash', 'value' => '8.0% Max', 'unit' => '%', 'test_method' => 'ASTA 3.0'],
                    ['spec_group' => 'Chemical Parameters', 'parameter' => 'Acid Insoluble Ash', 'value' => '1.0% Max', 'unit' => '%', 'test_method' => 'ASTA 4.0'],
                    ['spec_group' => 'Food Safety', 'parameter' => 'Pesticide Residues', 'value' => 'Compliant with EU MRL / US FDA', 'unit' => 'ppm', 'test_method' => 'GC-MS / LC-MS'],
                ],
            ],
            [
                'category' => 'spices',
                'name' => 'Coriander Seeds (Dhaniya)',
                'slug' => 'coriander-seeds',
                'sku' => 'ADE-SP-COR',
                'short_description' => 'Whole golden-green coriander seeds with aromatic citrus-spice notes.',
                'description' => 'Sourced from the fertile Ramganj and Gujarat border agricultural hubs. Whole, unbroken globose fruits cleaned to remove chaff and hollow grains. High volatile oil content imparts signature curry aroma.',
                'origin' => 'Rajasthan & Gujarat, India',
                'grade_variety' => 'Eagle Quality, Scooter Quality, Badami, Sortex Cleaned',
                'hs_code' => '0909.21.90',
                'moq' => 10.00,
                'moq_unit' => 'MT (1 x 20ft FCL - light bulk)',
                'available_quantity' => '2,500 MT',
                'shelf_life' => '24 Months',
                'storage_conditions' => 'Cool dry warehouse',
                'packaging_summary' => '20kg / 25kg PP Woven Bags or Jute Bags',
                'loading_summary' => '10 MT in 20ft FCL, 21 MT in 40ft HC',
                'is_featured' => true,
                'specs' => [
                    ['spec_group' => 'Physical Parameters', 'parameter' => 'Purity', 'value' => '98.5% - 99.0% Min', 'unit' => '%', 'test_method' => 'ASTA'],
                    ['spec_group' => 'Physical Parameters', 'parameter' => 'Moisture', 'value' => '9.0% Max', 'unit' => '%', 'test_method' => 'ASTA 2.0'],
                    ['spec_group' => 'Chemical Parameters', 'parameter' => 'Volatile Oil', 'value' => '0.3% - 0.5% Min', 'unit' => '% v/w', 'test_method' => 'ASTA 5.0'],
                    ['spec_group' => 'Physical Parameters', 'parameter' => 'Splits', 'value' => '< 5.0% Max', 'unit' => '%', 'test_method' => 'Visual Sort'],
                ],
            ],
            [
                'category' => 'spices',
                'name' => 'Fennel Seeds (Saunf)',
                'slug' => 'fennel-seeds',
                'sku' => 'ADE-SP-FEN',
                'short_description' => 'Sweet, aromatic green bold fennel seeds, machine cleaned & Sortexed.',
                'description' => 'Cultivated in North Gujarat (Unjha and Mehsana). Distinguished by uniform green hue, prominent ribbing, and pleasant sweet aniseed flavor. Used in confectioneries, herbal teas, and spice seasonings.',
                'origin' => 'Gujarat, India',
                'grade_variety' => 'Lucknow Bold Green, Abu Road Green, Regular Sortex',
                'hs_code' => '0909.61.39',
                'moq' => 13.00,
                'moq_unit' => 'MT',
                'available_quantity' => '2,000 MT',
                'shelf_life' => '24 Months',
                'storage_conditions' => 'Cool storage, protected from sunlight to preserve green color',
                'packaging_summary' => '25kg / 50kg PP Bags, Jute Bags',
                'loading_summary' => '13 MT in 20ft FCL',
                'is_featured' => false,
                'specs' => [
                    ['spec_group' => 'Physical Parameters', 'parameter' => 'Purity', 'value' => '99.0% Min', 'unit' => '%', 'test_method' => 'ASTA'],
                    ['spec_group' => 'Physical Parameters', 'parameter' => 'Moisture', 'value' => '9.0% Max', 'unit' => '%', 'test_method' => 'ASTA 2.0'],
                    ['spec_group' => 'Chemical Parameters', 'parameter' => 'Volatile Oil', 'value' => '1.5% - 2.0% Min', 'unit' => '% v/w', 'test_method' => 'Distillation'],
                ],
            ],
            [
                'category' => 'spices',
                'name' => 'Fenugreek Seeds (Methi)',
                'slug' => 'fenugreek-seeds',
                'sku' => 'ADE-SP-MTH',
                'short_description' => 'Golden yellow rectangular fenugreek seeds, Sortex cleaned 99% purity.',
                'description' => 'Hard, golden-brown rhombic seeds with aromatic maple-like bittersweet notes. Widely utilized in Middle Eastern cuisine, spice blends, and dietary nutraceutical formulations.',
                'origin' => 'Rajasthan & Gujarat, India',
                'grade_variety' => 'Machine Cleaned 99% & Sortex Cleaned 99.5%',
                'hs_code' => '0910.99.12',
                'moq' => 19.00,
                'moq_unit' => 'MT',
                'available_quantity' => '2,200 MT',
                'shelf_life' => '24 Months',
                'storage_conditions' => 'Cool dry warehouse',
                'packaging_summary' => '25kg / 50kg PP Woven Bags',
                'loading_summary' => '19 MT in 20ft FCL',
                'is_featured' => false,
                'specs' => [
                    ['spec_group' => 'Physical Parameters', 'parameter' => 'Purity', 'value' => '99.0% Min', 'unit' => '%', 'test_method' => 'ASTA'],
                    ['spec_group' => 'Physical Parameters', 'parameter' => 'Moisture', 'value' => '8.0% Max', 'unit' => '%', 'test_method' => 'AOAC'],
                ],
            ],
            [
                'category' => 'spices',
                'name' => 'Turmeric Fingers & Powder (Haldi)',
                'slug' => 'turmeric-fingers',
                'sku' => 'ADE-SP-TUR',
                'short_description' => 'Salem & Nizamabad polished whole turmeric fingers with high curcumin (3.0% - 5.0%+).',
                'description' => 'Bright golden-orange dried rhizomes. Double-polished on mechanical drums to remove outer soil skin. Tested for natural curcuminoid concentrations and zero artificial lead chromate colorants.',
                'origin' => 'South & Western India',
                'grade_variety' => 'Salem Polished, Nizamabad Finger, Bulb (Gatha)',
                'hs_code' => '0910.30.20',
                'moq' => 18.00,
                'moq_unit' => 'MT',
                'available_quantity' => '3,500 MT',
                'shelf_life' => '24 Months',
                'storage_conditions' => 'Cool, dry, dark warehouse',
                'packaging_summary' => '25kg / 50kg Jute Bags or PP Bags',
                'loading_summary' => '18 MT in 20ft FCL',
                'is_featured' => true,
                'specs' => [
                    ['spec_group' => 'Active Marker', 'parameter' => 'Curcumin Content', 'value' => '3.0% - 5.0% Min', 'unit' => '%', 'test_method' => 'HPLC / Spectrophotometry'],
                    ['spec_group' => 'Physical Parameters', 'parameter' => 'Moisture', 'value' => '10.0% Max', 'unit' => '%', 'test_method' => 'ASTA 2.0'],
                    ['spec_group' => 'Food Safety', 'parameter' => 'Chromate / Lead', 'value' => 'Negative / Absent', 'unit' => '', 'test_method' => 'AAS / ICP-MS'],
                ],
            ],
            [
                'category' => 'spices',
                'name' => 'Black Cumin Seeds (Kalonji / Nigella Sativa)',
                'slug' => 'black-cumin-seeds',
                'sku' => 'ADE-SP-BCM',
                'short_description' => 'Small jet-black triangular Nigella seeds with strong aromatic thymoquinone aroma.',
                'description' => 'Cleaned over air-screen destoners and micro-seed optical sorters. Renowned across global pharmaceutical, cosmetic, and artisanal baking sectors.',
                'origin' => 'Rajasthan & Gujarat, India',
                'grade_variety' => 'Sortex Cleaned 99.5% Purity',
                'hs_code' => '0909.31.29',
                'moq' => 10.00,
                'moq_unit' => 'MT',
                'available_quantity' => '1,000 MT',
                'shelf_life' => '24 Months',
                'storage_conditions' => 'Airtight dry container',
                'packaging_summary' => '25kg Paper / PP Bags',
                'loading_summary' => '16 MT in 20ft FCL',
                'is_featured' => false,
                'specs' => [
                    ['spec_group' => 'Physical Parameters', 'parameter' => 'Purity', 'value' => '99.5% Min', 'unit' => '%', 'test_method' => 'IS 1155'],
                    ['spec_group' => 'Physical Parameters', 'parameter' => 'Moisture', 'value' => '7.0% Max', 'unit' => '%', 'test_method' => 'AOAC'],
                ],
            ],

            // HERBS & SPECIALTY SEEDS
            [
                'category' => 'herbs-seeds',
                'name' => 'Chia Seeds (Black & White)',
                'slug' => 'chia-seeds',
                'sku' => 'ADE-HB-CHI',
                'short_description' => 'Machine Cleaned organic grade Chia seeds packed with Omega-3, antioxidants, and fiber.',
                'description' => 'Cultivated in dedicated agricultural zones with minimal pesticide exposure. Cleaned to 99.9% purity with zero weeds or foreign seeds, ideal for functional beverages, baking, and direct retail packing.',
                'origin' => 'Western India',
                'grade_variety' => 'Sortex Cleaned 99.9% Purity (Black / White)',
                'hs_code' => '1207.99.90',
                'moq' => 10.00,
                'moq_unit' => 'MT',
                'available_quantity' => '1,500 MT',
                'shelf_life' => '24 Months',
                'storage_conditions' => 'Cool dry warehouse below 20°C',
                'packaging_summary' => '25kg Paper Bags with inner liner',
                'loading_summary' => '18 MT in 20ft FCL',
                'is_featured' => true,
                'specs' => [
                    ['spec_group' => 'Physical Parameters', 'parameter' => 'Purity', 'value' => '99.9% Min', 'unit' => '%', 'test_method' => 'Visual / Gravimetric'],
                    ['spec_group' => 'Physical Parameters', 'parameter' => 'Moisture', 'value' => '7.0% Max', 'unit' => '%', 'test_method' => 'AOAC'],
                    ['spec_group' => 'Nutritional', 'parameter' => 'Omega-3 Fatty Acids', 'value' => '18.0g / 100g Min', 'unit' => 'g', 'test_method' => 'GC'],
                ],
            ],
            [
                'category' => 'herbs-seeds',
                'name' => 'Psyllium Husk & Powder (Isabgol)',
                'slug' => 'psyllium-husk',
                'sku' => 'ADE-HB-PSY',
                'short_description' => 'Pure white Plantago ovata husk flakes and powder with high mucilage swell volume.',
                'description' => 'Directly from Sidhpur and Gujarat processing mills. Available in 95%, 98%, and 99% purity flakes as well as 40 to 100 mesh powders for pharmaceutical and dietary fiber supplementation.',
                'origin' => 'Gujarat, India',
                'grade_variety' => 'Purity: 95%, 98%, 99% / 40-100 Mesh Powder',
                'hs_code' => '1211.90.32',
                'moq' => 5.00,
                'moq_unit' => 'MT',
                'available_quantity' => '1,200 MT',
                'shelf_life' => '36 Months',
                'storage_conditions' => 'Airtight packaging, strictly dry',
                'packaging_summary' => '25kg Fiber Drums / Paper Bags with PE barrier',
                'loading_summary' => '9.5 MT in 20ft FCL (Volumetric bulk)',
                'is_featured' => true,
                'specs' => [
                    ['spec_group' => 'Physical Parameters', 'parameter' => 'Purity', 'value' => '95.0% - 99.0%', 'unit' => '%', 'test_method' => 'USP / BP'],
                    ['spec_group' => 'Functional', 'parameter' => 'Swell Volume', 'value' => '40 - 50 ml/g Min', 'unit' => 'ml/g', 'test_method' => 'USP'],
                    ['spec_group' => 'Physical Parameters', 'parameter' => 'Moisture', 'value' => '10.0% Max', 'unit' => '%', 'test_method' => 'USP'],
                ],
            ],
            [
                'category' => 'herbs-seeds',
                'name' => 'Dry Ginger (Whole & Slices)',
                'slug' => 'dry-ginger',
                'sku' => 'ADE-HB-GNG',
                'short_description' => 'Sun-dried unbleached ginger fingers and dried slices with strong gingerol pungency.',
                'description' => 'Washed and sun-dried without chemical bleaches. Natural beige color, clean skin, fibrous texture, and strong essential oil profile for spice grinding and extraction.',
                'origin' => 'India',
                'grade_variety' => 'Unbleached Natural Whole & Sliced',
                'hs_code' => '0910.11.10',
                'moq' => 10.00,
                'moq_unit' => 'MT',
                'available_quantity' => '1,000 MT',
                'shelf_life' => '24 Months',
                'storage_conditions' => 'Dry, ventilated warehouse',
                'packaging_summary' => '25kg / 50kg Jute Bags',
                'loading_summary' => '13 MT in 20ft FCL',
                'is_featured' => false,
                'specs' => [
                    ['spec_group' => 'Physical Parameters', 'parameter' => 'Moisture', 'value' => '10.0% Max', 'unit' => '%', 'test_method' => 'ASTA'],
                    ['spec_group' => 'Chemical Parameters', 'parameter' => 'Volatile Oil', 'value' => '1.5% Min', 'unit' => '% v/w', 'test_method' => 'Steam Distillation'],
                ],
            ],
            [
                'category' => 'herbs-seeds',
                'name' => 'Mustard Seeds (Black & Yellow)',
                'slug' => 'mustard-seeds',
                'sku' => 'ADE-HB-MST',
                'short_description' => 'Cleaned bold black and bright yellow mustard seeds with high sinigrin pungency.',
                'description' => 'Directly sourced from Rajasthan and Gujarat mustard auctions. Destoned and Sortexed to 99.5% purity for table condiments, pickling, and oil pressing.',
                'origin' => 'Rajasthan & Gujarat, India',
                'grade_variety' => 'Small Black, Bold Black, Bright Yellow',
                'hs_code' => '1207.50.00',
                'moq' => 19.00,
                'moq_unit' => 'MT',
                'available_quantity' => '3,000 MT',
                'shelf_life' => '24 Months',
                'storage_conditions' => 'Cool dry warehouse',
                'packaging_summary' => '25kg / 50kg PP Bags',
                'loading_summary' => '19 MT in 20ft FCL',
                'is_featured' => false,
                'specs' => [
                    ['spec_group' => 'Physical Parameters', 'parameter' => 'Purity', 'value' => '99.0% - 99.5% Min', 'unit' => '%', 'test_method' => 'IS 1155'],
                    ['spec_group' => 'Chemical Parameters', 'parameter' => 'Oil Content', 'value' => '38.0% Min', 'unit' => '%', 'test_method' => 'Soxhlet'],
                ],
            ],

            // CHICKPEAS (GARBANZO BEANS)
            [
                'category' => 'chickpeas',
                'name' => 'Kabuli Chickpeas (Large Caliber)',
                'slug' => 'kabuli-chickpeas',
                'sku' => 'ADE-CK-KAB',
                'short_description' => 'Jumbo caliber (40/42, 42/44, 44/46 count) Kabuli Chickpeas with bright cream skins.',
                'description' => 'Hand-picked and gravity-separated Kabuli Chickpeas. High caliber (11mm - 12mm), bright white-cream color, zero dark spots, and high water-absorption ratio favored by hummus packers and Mediterranean canning brands.',
                'origin' => 'Madhya Pradesh & Maharashtra, India',
                'grade_variety' => 'Caliber: 40/42, 42/44, 44/46, 58/60, 75/80 Counts/Oz',
                'hs_code' => '0713.20.10',
                'moq' => 24.00,
                'moq_unit' => 'MT (1 x 20ft Heavy FCL)',
                'available_quantity' => '4,500 MT',
                'shelf_life' => '24 Months',
                'storage_conditions' => 'Cool, dry, fumigated warehouse',
                'packaging_summary' => '25kg / 50kg PP Woven Bags, New Jute Bags',
                'loading_summary' => '24 MT in 20ft FCL (High-density packing)',
                'is_featured' => true,
                'specs' => [
                    ['spec_group' => 'Physical Parameters', 'parameter' => 'Counts per Ounce', 'value' => '40/42, 42/44, 44/46, 58/60', 'unit' => 'Count/Oz', 'test_method' => 'Manual Count'],
                    ['spec_group' => 'Physical Parameters', 'parameter' => 'Seed Diameter', 'value' => '9mm - 12mm', 'unit' => 'mm', 'test_method' => 'Caliper / Sieve'],
                    ['spec_group' => 'Physical Parameters', 'parameter' => 'Moisture', 'value' => '10.0% Max', 'unit' => '%', 'test_method' => 'AOAC 925.10'],
                    ['spec_group' => 'Physical Parameters', 'parameter' => 'Defective / Discolored', 'value' => '< 1.5% Max', 'unit' => '%', 'test_method' => 'Visual Sort'],
                    ['spec_group' => 'Physical Parameters', 'parameter' => 'Foreign Matter', 'value' => '< 0.2% Max', 'unit' => '%', 'test_method' => 'Gravimetric'],
                ],
            ],
            [
                'category' => 'chickpeas',
                'name' => 'Desi Chickpeas (Brown Bengal Gram)',
                'slug' => 'desi-chickpeas',
                'sku' => 'ADE-CK-DES',
                'short_description' => 'Dark brown, angular Desi chickpeas packed with protein and dietary fiber.',
                'description' => 'Traditional Indian brown chickpeas harvested in Rajasthan and Gujarat. Highly nutritious, with robust hull and high protein content. Machine cleaned and polished for export.',
                'origin' => 'Western India',
                'grade_variety' => 'Machine Cleaned & Sortexed Desi Gram',
                'hs_code' => '0713.20.20',
                'moq' => 24.00,
                'moq_unit' => 'MT',
                'available_quantity' => '3,000 MT',
                'shelf_life' => '24 Months',
                'storage_conditions' => 'Standard dry warehouse',
                'packaging_summary' => '25kg / 50kg PP Bags',
                'loading_summary' => '24 MT in 20ft FCL',
                'is_featured' => false,
                'specs' => [
                    ['spec_group' => 'Physical Parameters', 'parameter' => 'Purity', 'value' => '99.0% Min', 'unit' => '%', 'test_method' => 'IS 1155'],
                    ['spec_group' => 'Physical Parameters', 'parameter' => 'Moisture', 'value' => '10.0% Max', 'unit' => '%', 'test_method' => 'AOAC'],
                    ['spec_group' => 'Nutritional', 'parameter' => 'Protein Content', 'value' => '20.0% Min', 'unit' => '%', 'test_method' => 'Kjeldahl'],
                ],
            ],
            [
                'category' => 'chickpeas',
                'name' => 'Roasted Chickpeas Split (Dalia / Roasted Chana Dal)',
                'slug' => 'roasted-chickpeas-split',
                'sku' => 'ADE-CK-RSP',
                'short_description' => 'Crunchy roasted split chickpeas without oil, golden yellow snack & flour ingredient.',
                'description' => 'Prepared by soaking, hulling, and sand-roasting Bengal gram splits without added oil or additives. Ready to eat, crunchy, high protein, and easily ground into roasted gram flour.',
                'origin' => 'Gujarat, India',
                'grade_variety' => 'Export Grade Roasted Split Dalia',
                'hs_code' => '2008.19.90',
                'moq' => 15.00,
                'moq_unit' => 'MT',
                'available_quantity' => '1,800 MT',
                'shelf_life' => '12 Months',
                'storage_conditions' => 'Airtight dry storage',
                'packaging_summary' => '25kg PP Bags with inner poly liner',
                'loading_summary' => '18 MT in 20ft FCL',
                'is_featured' => false,
                'specs' => [
                    ['spec_group' => 'Physical Parameters', 'parameter' => 'Moisture', 'value' => '5.0% Max', 'unit' => '%', 'test_method' => 'AOAC'],
                    ['spec_group' => 'Physical Parameters', 'parameter' => 'Broken / Powder', 'value' => '< 2.0% Max', 'unit' => '%', 'test_method' => 'Sieve'],
                ],
            ],

            // PULSES & LENTILS
            [
                'category' => 'pulses-lentils',
                'name' => 'Green Moong Beans (Whole)',
                'slug' => 'green-moong-beans',
                'sku' => 'ADE-PL-MNG',
                'short_description' => 'Uniform whole green moong beans with high germination and cooking softness.',
                'description' => 'Sourced from high-grade agricultural clusters. Cleaned through air aspirators and magnetic separators. High sprout germination (> 95%) makes them popular for bean sprout cultivation and Asian bean paste.',
                'origin' => 'Gujarat & Rajasthan, India',
                'grade_variety' => 'Shiny Green & Dull Green, Grade A Sortexed',
                'hs_code' => '0713.31.10',
                'moq' => 24.00,
                'moq_unit' => 'MT',
                'available_quantity' => '3,500 MT',
                'shelf_life' => '24 Months',
                'storage_conditions' => 'Cool dry warehouse',
                'packaging_summary' => '25kg / 50kg PP Woven Bags with PE liner',
                'loading_summary' => '24 MT in 20ft FCL',
                'is_featured' => true,
                'specs' => [
                    ['spec_group' => 'Physical Parameters', 'parameter' => 'Purity', 'value' => '99.0% Min', 'unit' => '%', 'test_method' => 'IS 1155'],
                    ['spec_group' => 'Physical Parameters', 'parameter' => 'Moisture', 'value' => '10.0% Max', 'unit' => '%', 'test_method' => 'AOAC 925.10'],
                    ['spec_group' => 'Functional', 'parameter' => 'Germination Rate', 'value' => '> 95.0%', 'unit' => '%', 'test_method' => 'Seed Germination Test'],
                ],
            ],
            [
                'category' => 'pulses-lentils',
                'name' => 'Moong Mogar (Washed Split Yellow Moong)',
                'slug' => 'moong-mogar',
                'sku' => 'ADE-PL-MMG',
                'short_description' => 'Dehulled, split bright yellow moong lentils, fast-cooking and easily digestible.',
                'description' => 'Skinless split moong lentils cleaned and polished. Highly valued in South Asian cuisine, dietary soups, and protein-enriched snack extrusions.',
                'origin' => 'Western India',
                'grade_variety' => 'Sortexed Dehulled Split Moong',
                'hs_code' => '0713.31.90',
                'moq' => 20.00,
                'moq_unit' => 'MT',
                'available_quantity' => '2,000 MT',
                'shelf_life' => '24 Months',
                'storage_conditions' => 'Dry warehouse',
                'packaging_summary' => '25kg PP Bags',
                'loading_summary' => '24 MT in 20ft FCL',
                'is_featured' => false,
                'specs' => [
                    ['spec_group' => 'Physical Parameters', 'parameter' => 'Purity', 'value' => '99.5% Min', 'unit' => '%', 'test_method' => 'IS 1155'],
                    ['spec_group' => 'Physical Parameters', 'parameter' => 'Moisture', 'value' => '10.0% Max', 'unit' => '%', 'test_method' => 'AOAC'],
                ],
            ],
            [
                'category' => 'pulses-lentils',
                'name' => 'Toor Dal (Pigeon Peas - Oily & Non-Oily)',
                'slug' => 'toor-dal',
                'sku' => 'ADE-PL-TOR',
                'short_description' => 'Gujarat polished yellow pigeon pea splits, available in natural non-oily and caster-oily grades.',
                'description' => 'Cleaned, split, and sized in high-capacity dal mills. High protein content, rich aroma upon cooking, and long shelf stability.',
                'origin' => 'Gujarat & Maharashtra, India',
                'grade_variety' => 'Non-Oily & Gujarat Oily Toor Dal',
                'hs_code' => '0713.60.00',
                'moq' => 22.00,
                'moq_unit' => 'MT',
                'available_quantity' => '2,500 MT',
                'shelf_life' => '24 Months',
                'storage_conditions' => 'Dry warehouse',
                'packaging_summary' => '25kg / 50kg PP Bags',
                'loading_summary' => '24 MT in 20ft FCL',
                'is_featured' => false,
                'specs' => [
                    ['spec_group' => 'Physical Parameters', 'parameter' => 'Purity', 'value' => '99.5% Min', 'unit' => '%', 'test_method' => 'IS 1155'],
                    ['spec_group' => 'Physical Parameters', 'parameter' => 'Moisture', 'value' => '11.0% Max', 'unit' => '%', 'test_method' => 'AOAC'],
                ],
            ],

            // DEHYDRATED VEGETABLES
            [
                'category' => 'dehydrated-vegetables',
                'name' => 'Dehydrated White Onion Flakes & Kibbled',
                'slug' => 'dehydrated-white-onion-flakes',
                'sku' => 'ADE-DV-ONF',
                'short_description' => 'Mahuva processed snow-white dehydrated onion flakes, pungent allicin flavor.',
                'description' => 'Mahuva in Gujarat is the dehydration capital of India. Fresh white onions are peeled, washed, sliced, and hot-air dried under continuous belt driers. Low moisture (< 5%) guarantees crispy texture and shelf stability without sulfites.',
                'origin' => 'Mahuva, Gujarat, India',
                'grade_variety' => 'A-Grade Snow White Flakes / Kibbled',
                'hs_code' => '0712.20.00',
                'moq' => 8.00,
                'moq_unit' => 'MT (1 x 40ft HC - volumetric cargo)',
                'available_quantity' => '3,000 MT',
                'shelf_life' => '24 Months',
                'storage_conditions' => 'Airtight poly-lined cartons below 20°C',
                'packaging_summary' => '14kg / 15kg Double Poly-lined 5-ply Corrugated Cartons',
                'loading_summary' => '8 MT in 20ft FCL, 16.5 MT in 40ft HC Container',
                'is_featured' => true,
                'specs' => [
                    ['spec_group' => 'Physical Parameters', 'parameter' => 'Moisture', 'value' => '5.0% Max', 'unit' => '%', 'test_method' => 'AOAC 925.10'],
                    ['spec_group' => 'Physical Parameters', 'parameter' => 'Flake Size', 'value' => '8mm - 25mm (Kibbled)', 'unit' => 'mm', 'test_method' => 'Sieve Analysis'],
                    ['spec_group' => 'Physical Parameters', 'parameter' => 'Color', 'value' => 'Natural White / Creamy White', 'unit' => '', 'test_method' => 'Visual / Hunter Lab'],
                    ['spec_group' => 'Physical Parameters', 'parameter' => 'Defects / Skin', 'value' => '< 1.0% Max', 'unit' => '%', 'test_method' => 'Gravimetric'],
                    ['spec_group' => 'Microbiological', 'parameter' => 'Total Plate Count (TPC)', 'value' => '< 100,000 cfu/g (or Low Bacteria < 10,000)', 'unit' => 'cfu/g', 'test_method' => 'BAM'],
                    ['spec_group' => 'Microbiological', 'parameter' => 'E. Coli / Salmonella', 'value' => 'Negative in 25g', 'unit' => '/25g', 'test_method' => 'ISO'],
                ],
            ],
            [
                'category' => 'dehydrated-vegetables',
                'name' => 'Dehydrated Red Onion Flakes & Powder',
                'slug' => 'dehydrated-red-onion-flakes',
                'sku' => 'ADE-DV-ONR',
                'short_description' => 'Natural dark red dehydrated onion flakes and fine powder, rich savory pungency.',
                'description' => 'Processed from authentic Saurashtra red onions. Delivers intense aroma and natural pinkish-red hue suited for seasoning rubs, soup bases, and canned culinary foods.',
                'origin' => 'Mahuva, Gujarat, India',
                'grade_variety' => 'Red Flakes, Minced, and 100-Mesh Powder',
                'hs_code' => '0712.20.00',
                'moq' => 8.00,
                'moq_unit' => 'MT',
                'available_quantity' => '2,000 MT',
                'shelf_life' => '24 Months',
                'storage_conditions' => 'Airtight cool dry warehouse',
                'packaging_summary' => '14kg / 20kg Poly-lined Cartons / 25kg Kraft Bags',
                'loading_summary' => '8 MT in 20ft FCL, 16 MT in 40ft HC',
                'is_featured' => false,
                'specs' => [
                    ['spec_group' => 'Physical Parameters', 'parameter' => 'Moisture', 'value' => '5.0% Max', 'unit' => '%', 'test_method' => 'AOAC'],
                    ['spec_group' => 'Microbiology', 'parameter' => 'Total Plate Count', 'value' => '< 100,000 cfu/g', 'unit' => 'cfu/g', 'test_method' => 'BAM'],
                ],
            ],
            [
                'category' => 'dehydrated-vegetables',
                'name' => 'Dehydrated Garlic Flakes & Cloves',
                'slug' => 'dehydrated-garlic-flakes',
                'sku' => 'ADE-DV-GAR',
                'short_description' => 'Mechanically peeled & dehydrated garlic flakes with pungent allicin aroma.',
                'description' => 'White to creamy yellow dehydrated garlic cloves and flakes. Mechanically destoned, metal detected, and laser sorted to eliminate root ends and foreign matter.',
                'origin' => 'Gujarat & Madhya Pradesh, India',
                'grade_variety' => 'Commercial A-Grade Garlic Flakes',
                'hs_code' => '0712.90.20',
                'moq' => 10.00,
                'moq_unit' => 'MT',
                'available_quantity' => '2,000 MT',
                'shelf_life' => '24 Months',
                'storage_conditions' => 'Cool dry warehouse',
                'packaging_summary' => '20kg / 25kg Double PE-lined 5-ply Cartons',
                'loading_summary' => '11 MT in 20ft FCL, 22 MT in 40ft HC',
                'is_featured' => true,
                'specs' => [
                    ['spec_group' => 'Physical Parameters', 'parameter' => 'Moisture', 'value' => '6.0% Max', 'unit' => '%', 'test_method' => 'AOAC 925.10'],
                    ['spec_group' => 'Physical Parameters', 'parameter' => 'Purity', 'value' => '99.5% Min', 'unit' => '%', 'test_method' => 'Visual Sort'],
                    ['spec_group' => 'Microbiological', 'parameter' => 'Salmonella', 'value' => 'Negative in 25g', 'unit' => '/25g', 'test_method' => 'ISO 6579'],
                ],
            ],
            [
                'category' => 'dehydrated-vegetables',
                'name' => 'Dehydrated Garlic Chopped, Granules & Powder',
                'slug' => 'dehydrated-garlic-granules',
                'sku' => 'ADE-DV-GRP',
                'short_description' => 'Sieved garlic granulations: Chopped (3-5mm), Minced (1-3mm), Granules (40-60 mesh), Powder (100 mesh).',
                'description' => 'Precision-milled dehydrated garlic particles free from caking or starch fillers. Ideal for dry seasoning blends, snack coating, instant noodles, and processed meats.',
                'origin' => 'Gujarat, India',
                'grade_variety' => 'Chopped, Minced, Granules, 100-Mesh Powder',
                'hs_code' => '0712.90.20',
                'moq' => 10.00,
                'moq_unit' => 'MT',
                'available_quantity' => '2,000 MT',
                'shelf_life' => '24 Months',
                'storage_conditions' => 'Sealed airtight cartons',
                'packaging_summary' => '20kg / 25kg Poly-lined Cartons / Bags',
                'loading_summary' => '14 MT in 20ft FCL',
                'is_featured' => false,
                'specs' => [
                    ['spec_group' => 'Physical Parameters', 'parameter' => 'Moisture', 'value' => '6.0% Max', 'unit' => '%', 'test_method' => 'AOAC'],
                    ['spec_group' => 'Physical Parameters', 'parameter' => 'Mesh Consistency', 'value' => '> 95% within specified mesh cut', 'unit' => '%', 'test_method' => 'Ro-Tap Sieve'],
                ],
            ],

            // GRAINS & MILLING PRODUCTS
            [
                'category' => 'grains-milling',
                'name' => 'Yellow Corn / Maize Grain',
                'slug' => 'yellow-corn-maize',
                'sku' => 'ADE-GR-CRN',
                'short_description' => 'Machine cleaned non-GMO yellow maize, moisture < 13.5%, high starch.',
                'description' => 'Cleaned yellow corn harvested from Central and Western India. High test weight, low broken kernels, and free from weevils, suitable for animal feed compounding, starch extraction, and food processing.',
                'origin' => 'Western India',
                'grade_variety' => 'Non-GMO Yellow Maize Grade 1 & 2',
                'hs_code' => '1005.90.00',
                'moq' => 24.00,
                'moq_unit' => 'MT',
                'available_quantity' => '10,000 MT',
                'shelf_life' => '12 Months',
                'storage_conditions' => 'Dry, ventilated bulk silo or warehouse',
                'packaging_summary' => '50kg PP Woven Bags / Bulk container liner',
                'loading_summary' => '24 MT in 20ft FCL',
                'is_featured' => true,
                'specs' => [
                    ['spec_group' => 'Physical Parameters', 'parameter' => 'Moisture', 'value' => '13.5% Max', 'unit' => '%', 'test_method' => 'AOAC'],
                    ['spec_group' => 'Physical Parameters', 'parameter' => 'Foreign Matter', 'value' => '< 1.5% Max', 'unit' => '%', 'test_method' => 'IS 4333'],
                    ['spec_group' => 'Physical Parameters', 'parameter' => 'Broken Kernels', 'value' => '< 3.0% Max', 'unit' => '%', 'test_method' => 'IS 4333'],
                    ['spec_group' => 'Food Safety', 'parameter' => 'Aflatoxin Total', 'value' => '< 20 ppb', 'unit' => 'ppb', 'test_method' => 'HPLC'],
                ],
            ],
            [
                'category' => 'grains-milling',
                'name' => 'Corn Grits & Corn Flour',
                'slug' => 'corn-grits-flour',
                'sku' => 'ADE-GR-CRG',
                'short_description' => 'Degermed yellow corn grits and fine corn flour for extruded snacks and cereals.',
                'description' => 'Milled from degermed non-GMO yellow corn. Clean golden granules with low fat content (< 1.0%) preventing rancidity and ensuring maximum puff expansion in snack extruders.',
                'origin' => 'Gujarat, India',
                'grade_variety' => 'Grits Mesh 101/108, Fine Corn Flour',
                'hs_code' => '1103.13.00',
                'moq' => 20.00,
                'moq_unit' => 'MT',
                'available_quantity' => '3,000 MT',
                'shelf_life' => '12 Months',
                'storage_conditions' => 'Dry warehouse',
                'packaging_summary' => '25kg / 50kg PP Bags with inner liner',
                'loading_summary' => '22 MT in 20ft FCL',
                'is_featured' => false,
                'specs' => [
                    ['spec_group' => 'Chemical Parameters', 'parameter' => 'Fat Content', 'value' => '< 1.0% Max', 'unit' => '%', 'test_method' => 'Soxhlet'],
                    ['spec_group' => 'Physical Parameters', 'parameter' => 'Moisture', 'value' => '12.0% Max', 'unit' => '%', 'test_method' => 'AOAC'],
                ],
            ],
            [
                'category' => 'grains-milling',
                'name' => 'Milling Wheat (Lokwan & Sharbati)',
                'slug' => 'milling-wheat',
                'sku' => 'ADE-GR-WHT',
                'short_description' => 'Hard golden milling wheat with high protein (12.5%+), high falling number, strong gluten.',
                'description' => 'Directly sourced from Madhya Pradesh and Gujarat silos. Heavy hectolitre weight (78-80 kg/hl), high wet gluten (28%+), delivering exceptional loaf volume and water absorption for industrial bakeries.',
                'origin' => 'Western & Central India',
                'grade_variety' => 'Lokwan Hard Wheat, Sharbati Premium',
                'hs_code' => '1001.99.10',
                'moq' => 24.00,
                'moq_unit' => 'MT',
                'available_quantity' => '8,000 MT',
                'shelf_life' => '12 Months',
                'storage_conditions' => 'Dry ventilated storage',
                'packaging_summary' => '50kg PP Woven Bags',
                'loading_summary' => '24 MT in 20ft FCL',
                'is_featured' => true,
                'specs' => [
                    ['spec_group' => 'Chemical Parameters', 'parameter' => 'Protein Content', 'value' => '12.5% - 13.5% Min', 'unit' => '% dry basis', 'test_method' => 'Kjeldahl'],
                    ['spec_group' => 'Physical Parameters', 'parameter' => 'Hectolitre Weight', 'value' => '78 - 80 kg/hl', 'unit' => 'kg/hl', 'test_method' => 'Chondrometer'],
                    ['spec_group' => 'Functional', 'parameter' => 'Falling Number', 'value' => '> 350 seconds', 'unit' => 'sec', 'test_method' => 'Hagberg'],
                    ['spec_group' => 'Functional', 'parameter' => 'Wet Gluten', 'value' => '> 28.0%', 'unit' => '%', 'test_method' => 'Glutomatic'],
                ],
            ],
            [
                'category' => 'grains-milling',
                'name' => 'Pearl Millet (Bajra Grain)',
                'slug' => 'pearl-millet-bajra',
                'sku' => 'ADE-GR-MLT',
                'short_description' => 'Grey-green pearl millet grains, high iron and gluten-free dietary nutrition.',
                'description' => 'Harvested from arid Gujarat zones. Sized and cleaned to eliminate sand and husk. Ideal for health food porridge, gluten-free baking flour, and poultry feeding.',
                'origin' => 'Gujarat & Rajasthan, India',
                'grade_variety' => 'Machine Cleaned & Sortexed Bajra',
                'hs_code' => '1008.21.00',
                'moq' => 24.00,
                'moq_unit' => 'MT',
                'available_quantity' => '4,000 MT',
                'shelf_life' => '12 Months',
                'storage_conditions' => 'Dry warehouse',
                'packaging_summary' => '25kg / 50kg PP Bags',
                'loading_summary' => '24 MT in 20ft FCL',
                'is_featured' => false,
                'specs' => [
                    ['spec_group' => 'Physical Parameters', 'parameter' => 'Purity', 'value' => '99.0% Min', 'unit' => '%', 'test_method' => 'IS 4333'],
                    ['spec_group' => 'Physical Parameters', 'parameter' => 'Moisture', 'value' => '11.0% Max', 'unit' => '%', 'test_method' => 'AOAC'],
                ],
            ],

            // ANIMAL FEED & OIL MEALS
            [
                'category' => 'animal-feed',
                'name' => 'Corn DDGS (28% Protein)',
                'slug' => 'corn-ddgs',
                'sku' => 'ADE-AF-DDG',
                'short_description' => 'Distillers Dried Grains with Solubles (DDGS), 28% crude protein, high bypass protein & phosphorus.',
                'description' => 'Golden yellow, free-flowing corn DDGS derived from grain-based ethanol fermentation. High energy and bypass protein value, an exceptional economical protein supplement for poultry, cattle, and aquaculture diets.',
                'origin' => 'Western India',
                'grade_variety' => 'High Protein Corn DDGS 28%',
                'hs_code' => '2303.30.00',
                'moq' => 20.00,
                'moq_unit' => 'MT',
                'available_quantity' => '5,000 MT',
                'shelf_life' => '6 Months',
                'storage_conditions' => 'Cool, dry, shaded warehouse',
                'packaging_summary' => '50kg PP Bags / 1000kg Big Bags',
                'loading_summary' => '20 MT in 20ft FCL',
                'is_featured' => true,
                'specs' => [
                    ['spec_group' => 'Nutritional', 'parameter' => 'Crude Protein', 'value' => '27.0% - 29.0% Min', 'unit' => '%', 'test_method' => 'Kjeldahl'],
                    ['spec_group' => 'Nutritional', 'parameter' => 'Crude Fat', 'value' => '8.0% - 10.0% Min', 'unit' => '%', 'test_method' => 'Soxhlet'],
                    ['spec_group' => 'Physical Parameters', 'parameter' => 'Moisture', 'value' => '10.0% Max', 'unit' => '%', 'test_method' => 'AOAC'],
                    ['spec_group' => 'Nutritional', 'parameter' => 'Crude Fiber', 'value' => '8.0% Max', 'unit' => '%', 'test_method' => 'AOAC'],
                ],
            ],
            [
                'category' => 'animal-feed',
                'name' => 'De-oiled Soybean Meal (DOC Hi-Pro 46-48%)',
                'slug' => 'soybean-meal-doc',
                'sku' => 'ADE-AF-SOY',
                'short_description' => 'Golden toasted de-oiled soybean meal flakes, Hi-Pro 46-48% protein, low urease activity.',
                'description' => 'Extracted from non-GMO Indian soybeans. Toasted to deactivate trypsin inhibitors and urease enzymes, providing maximum amino acid bioavailability for poultry broilers, layers, and shrimp aquaculture.',
                'origin' => 'Central & Western India',
                'grade_variety' => 'Hi-Pro Non-GMO Soybean Meal (DOC)',
                'hs_code' => '2304.00.10',
                'moq' => 20.00,
                'moq_unit' => 'MT',
                'available_quantity' => '8,000 MT',
                'shelf_life' => '6 Months',
                'storage_conditions' => 'Well-ventilated dry storage',
                'packaging_summary' => '50kg PP Woven Bags / 1000kg FIBC Bags',
                'loading_summary' => '20 MT in 20ft FCL, 26 MT in 40ft FCL',
                'is_featured' => true,
                'specs' => [
                    ['spec_group' => 'Nutritional', 'parameter' => 'Crude Protein (N x 6.25)', 'value' => '46.0% - 48.0% Min', 'unit' => '%', 'test_method' => 'Kjeldahl'],
                    ['spec_group' => 'Physical Parameters', 'parameter' => 'Moisture', 'value' => '11.0% Max', 'unit' => '%', 'test_method' => 'AOAC 925.10'],
                    ['spec_group' => 'Nutritional', 'parameter' => 'Crude Fiber', 'value' => '6.0% Max', 'unit' => '%', 'test_method' => 'AOAC'],
                    ['spec_group' => 'Quality Index', 'parameter' => 'Urease Activity (pH rise)', 'value' => '0.05 - 0.20 Max', 'unit' => 'pH unit', 'test_method' => 'AOCS Ba 9-58'],
                    ['spec_group' => 'Nutritional', 'parameter' => 'Sand / Silica', 'value' => '1.5% Max', 'unit' => '%', 'test_method' => 'Gravimetric'],
                ],
            ],
            [
                'category' => 'animal-feed',
                'name' => 'De-oiled Rice Bran (DORB)',
                'slug' => 'de-oiled-rice-bran',
                'sku' => 'ADE-AF-DRB',
                'short_description' => 'Clean de-oiled rice bran meal, 14-16% protein, cost-effective fiber and minerals.',
                'description' => 'High-quality DORB meal extracted from fresh rice bran. Palatable, rich in phosphorus and B-complex vitamins, an established staple in commercial cattle and carp fish feeding.',
                'origin' => 'Western India',
                'grade_variety' => 'Standard DORB Mash / Pellets',
                'hs_code' => '2306.90.90',
                'moq' => 20.00,
                'moq_unit' => 'MT',
                'available_quantity' => '5,000 MT',
                'shelf_life' => '6 Months',
                'storage_conditions' => 'Dry warehouse',
                'packaging_summary' => '50kg PP Woven Bags',
                'loading_summary' => '20 MT in 20ft FCL',
                'is_featured' => false,
                'specs' => [
                    ['spec_group' => 'Nutritional', 'parameter' => 'Crude Protein', 'value' => '14.0% - 16.0% Min', 'unit' => '%', 'test_method' => 'Kjeldahl'],
                    ['spec_group' => 'Nutritional', 'parameter' => 'Crude Fiber', 'value' => '12.0% - 14.0% Max', 'unit' => '%', 'test_method' => 'AOAC'],
                    ['spec_group' => 'Physical Parameters', 'parameter' => 'Silica / Sand', 'value' => '< 4.0% Max', 'unit' => '%', 'test_method' => 'Acid Insoluble'],
                ],
            ],
            [
                'category' => 'animal-feed',
                'name' => 'Rapeseed / Mustard Extraction Meal',
                'slug' => 'rapeseed-meal',
                'sku' => 'ADE-AF-RAP',
                'short_description' => 'High-protein (36-38%) rapeseed cake meal, balanced amino acid matrix for cattle feeds.',
                'description' => 'Extracted from natural Indian mustard and rapeseed. Highly balanced methionine and cystine content, preferred in ruminant diets to increase milk yield and fat content.',
                'origin' => 'Rajasthan & Gujarat, India',
                'grade_variety' => 'Toasted Rapeseed Meal Flakes / Mash',
                'hs_code' => '2306.41.00',
                'moq' => 20.00,
                'moq_unit' => 'MT',
                'available_quantity' => '6,000 MT',
                'shelf_life' => '6 Months',
                'storage_conditions' => 'Dry ventilated storage',
                'packaging_summary' => '50kg PP Bags / Bulk container liner',
                'loading_summary' => '20 MT in 20ft FCL',
                'is_featured' => false,
                'specs' => [
                    ['spec_group' => 'Nutritional', 'parameter' => 'Crude Protein', 'value' => '36.0% - 38.0% Min', 'unit' => '%', 'test_method' => 'Kjeldahl'],
                    ['spec_group' => 'Physical Parameters', 'parameter' => 'Moisture', 'value' => '10.0% Max', 'unit' => '%', 'test_method' => 'AOAC'],
                    ['spec_group' => 'Nutritional', 'parameter' => 'Crude Fiber', 'value' => '9.0% Max', 'unit' => '%', 'test_method' => 'AOAC'],
                ],
            ],
        ];

        $sortIndex = 1;
        foreach ($products as $pData) {
            $cat = $categories[$pData['category']] ?? null;
            if (!$cat) {
                continue;
            }

            $specs = $pData['specs'] ?? [];
            unset($pData['category'], $pData['specs']);

            $pData['category_id'] = $cat->id;
            $pData['is_active'] = true;
            $pData['sort_order'] = $sortIndex++;
            $pData['meta_title'] = "{$pData['name']} Exporter from India | Agro Dairy Export LLP";
            $pData['meta_description'] = Str::limit($pData['short_description'], 155);

            // Assign category image if product main_image not explicitly defined
            if (empty($pData['main_image'])) {
                $pData['main_image'] = $cat->image;
            }

            $product = Product::updateOrCreate(['slug' => $pData['slug']], $pData);

            // Seed specs
            $sOrder = 1;
            foreach ($specs as $s) {
                ProductSpecification::updateOrCreate(
                    [
                        'product_id' => $product->id,
                        'parameter' => $s['parameter'],
                    ],
                    [
                        'spec_group' => $s['spec_group'],
                        'value' => $s['value'],
                        'unit' => $s['unit'] ?? null,
                        'test_method' => $s['test_method'] ?? null,
                        'sort_order' => $sOrder++,
                    ]
                );
            }
        }
    }
}
