@extends('layouts.admin', ['title' => 'Quotation ' . $quotation->quotation_number])

@section('content')
<div class="space-y-8">
    <!-- Header -->
    <div class="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
            <div class="flex items-center gap-3">
                <h1 class="text-2xl font-bold font-display text-stone-900">{{ $quotation->quotation_number }}</h1>
                <span class="px-2.5 py-0.5 rounded-full text-xs font-bold uppercase
                    {{ $quotation->status == 'accepted' ? 'bg-emerald-100 text-emerald-800' :
                       ($quotation->status == 'sent' ? 'bg-blue-100 text-blue-800' :
                       ($quotation->status == 'draft' ? 'bg-amber-100 text-amber-800' : 'bg-stone-100 text-stone-700')) }}">
                    {{ $quotation->status }}
                </span>
            </div>
            <p class="text-xs text-stone-500 mt-1">Generated by {{ $quotation->createdBy?->name ?? 'Staff' }} on {{ $quotation->created_at->format('d M, Y H:i') }}</p>
        </div>

        <div class="flex items-center gap-3">
            <a href="{{ route('admin.quotations.preview_pdf', $quotation->id) }}" target="_blank" class="px-4 py-2 bg-stone-100 hover:bg-stone-200 text-stone-800 font-bold text-xs rounded-xl transition flex items-center gap-2 border border-stone-200">
                <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"/><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z"/></svg>
                <span>Preview PDF</span>
            </a>
            <a href="{{ route('admin.quotations.download_pdf', $quotation->id) }}" class="px-4 py-2 bg-emerald-800 hover:bg-emerald-900 text-white font-bold text-xs rounded-xl transition shadow flex items-center gap-2">
                <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4"/></svg>
                <span>Download Proforma PDF</span>
            </a>
            <a href="{{ route('admin.quotations.index') }}" class="px-3 py-2 bg-stone-100 text-stone-700 font-bold text-xs rounded-xl hover:bg-stone-200 transition">&larr; List</a>
        </div>
    </div>

    <div class="grid grid-cols-1 lg:grid-cols-12 gap-8">
        <!-- Left: Proforma Breakdown -->
        <div class="lg:col-span-8 space-y-8">
            <div class="bg-white p-6 md:p-8 rounded-2xl border border-stone-200 shadow-sm space-y-6">
                <div class="flex items-center justify-between pb-4 border-b border-stone-100">
                    <h2 class="text-lg font-bold font-display text-stone-900">Commercial Summary</h2>
                    <span class="font-mono text-xs font-bold text-stone-500">Validity Thru: {{ $quotation->valid_until ? $quotation->valid_until->format('d M, Y') : 'Perpetual' }}</span>
                </div>

                <div class="grid grid-cols-1 sm:grid-cols-3 gap-6 text-xs">
                    <div>
                        <span class="text-stone-400 block mb-0.5">Consignee Buyer</span>
                        <span class="font-bold text-stone-900 text-sm">{{ $quotation->inquiry?->name ?? 'Commercial Buyer' }}</span>
                        <div class="text-stone-500">{{ $quotation->inquiry?->company }}</div>
                    </div>
                    <div>
                        <span class="text-stone-400 block mb-0.5">Incoterm & Destination</span>
                        <span class="font-bold text-stone-900 text-sm">{{ $quotation->incoterm }}</span>
                        <div class="text-stone-500">POD: {{ $quotation->destination_port }}</div>
                    </div>
                    <div>
                        <span class="text-stone-400 block mb-0.5">Payment Terms</span>
                        <span class="font-bold text-stone-900 text-sm">{{ $quotation->payment_terms }}</span>
                    </div>
                </div>

                <!-- Line Items Table -->
                <div class="border border-stone-200 rounded-xl overflow-hidden mt-6">
                    <table class="w-full text-left text-xs">
                        <thead>
                            <tr class="bg-stone-50 text-stone-600 font-semibold border-b border-stone-200">
                                <th class="p-3">#</th>
                                <th class="p-3">Commodity & Specs</th>
                                <th class="p-3">Packaging</th>
                                <th class="p-3 text-right">Quantity</th>
                                <th class="p-3 text-right">Unit Rate ({{ $quotation->currency }})</th>
                                <th class="p-3 text-right">Amount ({{ $quotation->currency }})</th>
                            </tr>
                        </thead>
                        <tbody class="divide-y divide-stone-100 text-stone-700">
                            @foreach($quotation->items as $idx => $item)
                                <tr>
                                    <td class="p-3 font-mono text-stone-400">{{ $idx + 1 }}</td>
                                    <td class="p-3">
                                        <div class="font-bold text-stone-900">{{ $item->item_name }}</div>
                                        @if($item->grade_spec)
                                            <div class="text-[11px] text-stone-500">{{ $item->grade_spec }}</div>
                                        @endif
                                    </td>
                                    <td class="p-3">{{ $item->packaging ?? 'Export Grade Bags' }}</td>
                                    <td class="p-3 text-right font-medium">{{ number_format($item->quantity, 2) }} {{ $item->unit }}</td>
                                    <td class="p-3 text-right font-mono">{{ number_format($item->unit_price, 2) }}</td>
                                    <td class="p-3 text-right font-mono font-bold text-stone-900">{{ number_format($item->total_price, 2) }}</td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>

                <!-- Financial Totals -->
                <div class="bg-stone-50 p-6 rounded-xl border border-stone-200 space-y-2 text-xs max-w-sm ml-auto">
                    <div class="flex justify-between">
                        <span class="text-stone-500">Subtotal Cargo Value:</span>
                        <span class="font-mono font-bold">{{ $quotation->currency }} {{ number_format($quotation->subtotal, 2) }}</span>
                    </div>
                    @if($quotation->freight > 0)
                        <div class="flex justify-between">
                            <span class="text-stone-500">Ocean Freight:</span>
                            <span class="font-mono font-bold">{{ $quotation->currency }} {{ number_format($quotation->freight, 2) }}</span>
                        </div>
                    @endif
                    @if($quotation->insurance > 0)
                        <div class="flex justify-between">
                            <span class="text-stone-500">Marine Insurance:</span>
                            <span class="font-mono font-bold">{{ $quotation->currency }} {{ number_format($quotation->insurance, 2) }}</span>
                        </div>
                    @endif
                    @if($quotation->other_charges > 0)
                        <div class="flex justify-between">
                            <span class="text-stone-500">Other Port Charges:</span>
                            <span class="font-mono font-bold">{{ $quotation->currency }} {{ number_format($quotation->other_charges, 2) }}</span>
                        </div>
                    @endif
                    <div class="flex justify-between pt-2 border-t border-stone-200 text-sm font-bold text-stone-900">
                        <span>Grand Total ({{ $quotation->incoterm }}):</span>
                        <span class="font-mono text-emerald-900">{{ $quotation->currency }} {{ number_format($quotation->grand_total, 2) }}</span>
                    </div>
                </div>

                @if($quotation->terms_and_conditions)
                    <div class="p-4 bg-stone-50 rounded-xl border border-stone-200 text-xs">
                        <span class="font-bold text-stone-700 block mb-1">Contract Conditions:</span>
                        <p class="text-stone-600 leading-relaxed">{{ $quotation->terms_and_conditions }}</p>
                    </div>
                @endif
            </div>
        </div>

        <!-- Right: Status Control & Actions -->
        <div class="lg:col-span-4 space-y-6">
            <div class="bg-white p-6 rounded-2xl border border-stone-200 shadow-sm">
                <h3 class="text-base font-bold font-display text-stone-900 mb-4">Update Quotation Lifecycle</h3>
                <form action="{{ route('admin.quotations.status', $quotation->id) }}" method="POST" class="space-y-4">
                    @csrf
                    <div>
                        <label for="status" class="block text-xs font-bold text-stone-700 mb-1">Quotation Status</label>
                        <select name="status" id="status" class="w-full px-4 py-2.5 bg-stone-50 border border-stone-300 rounded-xl text-xs font-bold">
                            <option value="draft" {{ $quotation->status == 'draft' ? 'selected' : '' }}>Draft</option>
                            <option value="sent" {{ $quotation->status == 'sent' ? 'selected' : '' }}>Sent to Buyer</option>
                            <option value="revised" {{ $quotation->status == 'revised' ? 'selected' : '' }}>Revised</option>
                            <option value="accepted" {{ $quotation->status == 'accepted' ? 'selected' : '' }}>Accepted / Contract Awarded</option>
                            <option value="rejected" {{ $quotation->status == 'rejected' ? 'selected' : '' }}>Rejected</option>
                            <option value="expired" {{ $quotation->status == 'expired' ? 'selected' : '' }}>Expired</option>
                        </select>
                    </div>

                    <button type="submit" class="w-full py-2.5 bg-emerald-800 hover:bg-emerald-900 text-white font-bold text-xs rounded-xl transition shadow">
                        Save Status Change
                    </button>
                </form>
            </div>

            @if($quotation->inquiry)
                <div class="bg-white p-6 rounded-2xl border border-stone-200 shadow-sm">
                    <h3 class="text-base font-bold font-display text-stone-900 mb-2">Connected RFQ Lead</h3>
                    <p class="text-xs text-stone-500 mb-4">View the customer inquiry CRM discussion that initiated this offer.</p>
                    <a href="{{ route('admin.inquiries.show', $quotation->inquiry_id) }}" class="inline-flex items-center gap-1.5 text-xs font-bold text-emerald-800 hover:underline">
                        <span>Open RFQ {{ $quotation->inquiry->inquiry_number }}</span> &rarr;
                    </a>
                </div>
            @endif
        </div>
    </div>
</div>
@endsection
